---
version: "3"
services:
  jackett: #Preform RSS loopup 
    image: "lscr.io/linuxserver/jackett:latest"
    container_name: "jackett"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - AUTO_UPDATE=true #optional
#     - RUN_OPTS=<run options here> #optional
    volumes:
      - ./jackett.config:/config
      - ./jackett.downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  flaresolverr: #Solves Capcha
    image: "ghcr.io/flaresolverr/flaresolverr:latest"
    container_name: "flaresolverr"
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=America/New_York
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped
