---
version: '3.3'
services:
  portainer:
    image: portainer/portainer-ee:latest
    container_name: portainer
    cap_add:
      - ALL
    volumes:
      - ./portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9443:9443 #WebUI
      - 8000:8000
    restart: always

  portainer_agent:
    image: portainer/agent:latest
    container_name: portainer_agent
    volumes:
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9001:9001
    restart: always

volumes:
  portainer_data:
